language: node_js
node_js:
  - "8.11.3"
deploy:
  provider: heroku
  api_key:
    secure: mf9SPoKQH7Nv/HDOyMbAAh0n465eVAkBKVCU1N6h/PAtESK8ck3rkrVIlWQZmRqy76gqtSsGucIRzDEyA/ZN8FCv7zTuX8+5r4S7hsQeEjyFei85PAezeYqeEjKDDwgN4X/90a8Qh8wjhqC3rN3cWg8QbyvlxGPqUNANeKrr4g11I68B2KQbGTtqH5cBH6Yj59VaOEdDbyFP+4+hQE6W5ic0GBU1VkF5FGsrucNHZAxQBMs15nLWDGuEZAHW6MrofJJpGNWdCsK8ijpESepn2k8z04rlnor3ShQU1zSHV+xr+/Gm+dvUt1JjS7gay2hdncQqnNgj3HWwhMGJboj6agFbtdlzBupNl25iul5+ilKd8t9r++00HrhVWo0QJ9t/tLMA8myM5uXSDPE9XdZA2whnLwMStTAJUYanDCEIJ7piYlJJ5dqCV3tYquGRVu6ECBL5Zdk0vkepEBU/8wwJ/MI+EfasyVq1EmKMMhZjH32O3WiPGMCAfJyipW3gNhkOFCKHHb/j26PFAsUNp602t6RDc+YbEUuJJshWuigev902MjPR5WIdH0UNdZe4tw170L6CNMZolghBSf93jIws/R9HOGEL/14IP3HwJkcpUgkAY8y8Yfkz8NIBxWop+eGclhbEL2WtzbPdW7c120ojNU+OeLT5Zjk56aRLQIdLqLA=
  on:
    tags: true
    all_branches: true
